*&---------------------------------------------------------------------*
*&  Include           ZMANAGEMENT_SCR
*&---------------------------------------------------------------------*

SELECTION-SCREEN: BEGIN OF BLOCK b1 WITH FRAME TITLE text-B01.
   SELECT-OPTIONS: s_ORDID  FOR ZCORDERS-ORDER_ID,
                   s_CLID   FOR ZCLIENTS-CLIENT_ID,
                   s_CNAME  FOR ZCLIENTS-CLIENT_NAME,
                   s_CLNAME FOR ZCLIENTS-CLIENT_LAST_NAME,
                   s_OCOUNT FOR ZCLIENTS-ORDER_COUNT,
                   s_ODATE  FOR ZCORDERS-ORDER_DATE,
                   s_OTIME  FOR ZCORDERS-ORDER_TIME,
                   s_TOTAL  FOR ZCORDERS-TOTAL,
                   s_PAYM   FOR ZCORDERS-PAYMENT_METHOD,
                   s_PROID  FOR ZPRODUCTS-PROD_ID,
                   s_PNAME  FOR ZPRODUCTS-PROD_NAME,
                   s_PPRICE FOR ZPRODUCTS-PROD_PRICE,
                   s_PSTOCK FOR ZPRODUCTS-PROD_QUANTITY,
                   s_PQUAN  FOR ZORDPRODUCTS-PROD_QUANTITY.
SELECTION-SCREEN: END OF BLOCK b1.

SELECTION-SCREEN: BEGIN OF BLOCK b2 WITH FRAME TITLE text-B02.
   SELECTION-SCREEN  BEGIN OF LINE.
   SELECTION-SCREEN POSITION 10.
   PARAMETERS: r_dis RADIOBUTTON GROUP grp1 DEFAULT 'X'.
   SELECTION-SCREEN  COMMENT 12(24) TEXT-R01 FOR FIELD r_dis.
   SELECTION-SCREEN POSITION 45.
   PARAMETERS: r_mng RADIOBUTTON GROUP grp1.
   SELECTION-SCREEN  COMMENT 47(24) TEXT-R02 FOR FIELD r_mng.
   SELECTION-SCREEN  END   OF LINE.

SELECTION-SCREEN: END OF BLOCK b2.

*SELECTION-SCREEN: BEGIN OF BLOCK b3 WITH FRAME TITLE text-B03.
*   SELECTION-SCREEN  BEGIN OF LINE.
*   SELECTION-SCREEN POSITION 10.
*   PARAMETERS: r_ov RADIOBUTTON GROUP grp2 DEFAULT 'X'.
*   SELECTION-SCREEN  COMMENT 12(24) TEXT-R03 FOR FIELD r_ov.
*   SELECTION-SCREEN POSITION 45.
*   PARAMETERS: r_cl RADIOBUTTON GROUP grp2.
*   SELECTION-SCREEN  COMMENT 47(24) TEXT-R04 FOR FIELD r_cl.
*   SELECTION-SCREEN  END   OF LINE.
*
*   SELECTION-SCREEN  BEGIN OF LINE.
*   SELECTION-SCREEN POSITION 10.
*   PARAMETERS: r_pr RADIOBUTTON GROUP grp2.
*   SELECTION-SCREEN  COMMENT 12(24) TEXT-R05 FOR FIELD r_ov.
*   SELECTION-SCREEN POSITION 45.
*   PARAMETERS: r_co RADIOBUTTON GROUP grp2.
*   SELECTION-SCREEN  COMMENT 47(24) TEXT-R06 FOR FIELD r_cl.
*   SELECTION-SCREEN  END   OF LINE.
*
*   SELECTION-SCREEN  BEGIN OF LINE.
*   SELECTION-SCREEN POSITION 10.
*   PARAMETERS: r_op RADIOBUTTON GROUP grp2.
*   SELECTION-SCREEN  COMMENT 12(24) TEXT-R07 FOR FIELD r_ov.
*   SELECTION-SCREEN  END   OF LINE.
*
*SELECTION-SCREEN: END OF BLOCK b3.

SELECTION-SCREEN: BEGIN OF BLOCK b4 WITH FRAME TITLE text-B04.
   PARAMETERS:     r_ndyn  RADIOBUTTON GROUP grp3 DEFAULT 'X',
                   r_dyn   RADIOBUTTON GROUP grp3.
SELECTION-SCREEN: END OF BLOCK b4.