*&---------------------------------------------------------------------*
*&  Include           ZMANAGEMENT_SCR
*&---------------------------------------------------------------------*

"__________________________________________________________________________
" UPLOADING APPROACH MODE
SELECTION-SCREEN: BEGIN OF BLOCK b1 WITH FRAME TITLE text-B01.
   PARAMETERS:     r_sear   RADIOBUTTON GROUP grp1 DEFAULT 'X' USER-COMMAND upl,
                   r_exce   RADIOBUTTON GROUP grp1.
SELECTION-SCREEN: END OF BLOCK b1.

"__________________________________________________________________________
" Search Criteria, View Mode and Search Approach  for DB UPLOADING
SELECTION-SCREEN: BEGIN OF BLOCK b2 WITH FRAME TITLE text-B02.
   SELECT-OPTIONS: s_ORDID  FOR ZCORDERS-ORDER_ID MODIF ID SG1,
                   s_CLID   FOR ZCLIENTS-CLIENT_ID MODIF ID SG1,
                   s_CNAME  FOR ZCLIENTS-CLIENT_NAME MODIF ID SG1,
                   s_CLNAME FOR ZCLIENTS-CLIENT_LAST_NAME MODIF ID SG1,
                   s_OCOUNT FOR ZCLIENTS-ORDER_COUNT MODIF ID SG1,
                   s_ODATE  FOR ZCORDERS-ORDER_DATE MODIF ID SG1,
                   s_OTIME  FOR ZCORDERS-ORDER_TIME MODIF ID SG1,
                   s_TOTAL  FOR ZCORDERS-TOTAL MODIF ID SG1,
                   s_PAYM   FOR ZCORDERS-PAYMENT_METHOD MODIF ID SG1,
                   s_PROID  FOR ZPRODUCTS-PROD_ID MODIF ID SG1,
                   s_PNAME  FOR ZPRODUCTS-PROD_NAME MODIF ID SG1,
                   s_PPRICE FOR ZPRODUCTS-PROD_PRICE MODIF ID SG1,
                   s_PSTOCK FOR ZPRODUCTS-PROD_QUANTITY MODIF ID SG1,
                   s_PQUAN  FOR ZORDPRODUCTS-PROD_QUANTITY MODIF ID SG1.
SELECTION-SCREEN: END OF BLOCK b2.

SELECTION-SCREEN: BEGIN OF BLOCK b3 WITH FRAME TITLE text-B03.
   SELECTION-SCREEN  BEGIN OF LINE.
   SELECTION-SCREEN POSITION 10.
   PARAMETERS: r_dis RADIOBUTTON GROUP grp2 DEFAULT 'X' MODIF ID SG1.
   SELECTION-SCREEN  COMMENT 12(24) TEXT-R01 FOR FIELD r_dis MODIF ID SG1.
   SELECTION-SCREEN POSITION 45.
   PARAMETERS: r_mng RADIOBUTTON GROUP grp2 MODIF ID SG1.
   SELECTION-SCREEN  COMMENT 47(24) TEXT-R02 FOR FIELD r_mng MODIF ID SG1.
   SELECTION-SCREEN  END   OF LINE.

SELECTION-SCREEN: END OF BLOCK b3.

*SELECTION-SCREEN: BEGIN OF BLOCK b4 WITH FRAME TITLE text-B04.
*   SELECTION-SCREEN  BEGIN OF LINE.
*   SELECTION-SCREEN POSITION 10.
*   PARAMETERS: r_ov RADIOBUTTON GROUP grp3 DEFAULT 'X' MODIF ID SG1.
*   SELECTION-SCREEN  COMMENT 12(24) TEXT-R03 FOR FIELD r_ov MODIF ID SG1.
*   SELECTION-SCREEN POSITION 45.
*   PARAMETERS: r_cl RADIOBUTTON GROUP grp3 MODIF ID SG1.
*   SELECTION-SCREEN  COMMENT 47(24) TEXT-R04 FOR FIELD r_cl MODIF ID SG1.
*   SELECTION-SCREEN  END   OF LINE.
*
*   SELECTION-SCREEN  BEGIN OF LINE.
*   SELECTION-SCREEN POSITION 10.
*   PARAMETERS: r_pr RADIOBUTTON GROUP grp3 MODIF ID SG1.
*   SELECTION-SCREEN  COMMENT 12(24) TEXT-R05 FOR FIELD r_ov MODIF ID SG1.
*   SELECTION-SCREEN POSITION 45.
*   PARAMETERS: r_co RADIOBUTTON GROUP grp3.
*   SELECTION-SCREEN  COMMENT 47(24) TEXT-R06 FOR FIELD r_cl MODIF ID SG1.
*   SELECTION-SCREEN  END   OF LINE.
*
*   SELECTION-SCREEN  BEGIN OF LINE.
*   SELECTION-SCREEN POSITION 10.
*   PARAMETERS: r_op RADIOBUTTON GROUP grp3 MODIF ID SG1.
*   SELECTION-SCREEN  COMMENT 12(24) TEXT-R07 FOR FIELD r_ov MODIF ID SG1.
*   SELECTION-SCREEN  END   OF LINE.
*
*SELECTION-SCREEN: END OF BLOCK b4.

SELECTION-SCREEN: BEGIN OF BLOCK b5 WITH FRAME TITLE text-B05.
   PARAMETERS:     r_ndyn  RADIOBUTTON GROUP grp4 DEFAULT 'X' MODIF ID SG1,
                   r_dyn   RADIOBUTTON GROUP grp4 MODIF ID SG1.
SELECTION-SCREEN: END OF BLOCK b5.

"__________________________________________________________________________
" PARAMETER FOR UPLOADING FROM EXCEL
SELECTION-SCREEN BEGIN OF BLOCK b6 WITH FRAME TITLE TEXT-B06.
PARAMETERS : p_ufile TYPE RLGRAP-FILENAME MODIF ID SG2.
SELECTION-SCREEN END OF BLOCK b6.

*SELECTION-SCREEN FUNCTION KEY 1.