*&---------------------------------------------------------------------*
*&  Include           ZMP_CAFETEST_O01
*&---------------------------------------------------------------------*

MODULE status_100 OUTPUT.
  SET PF-STATUS 'INITIAL_MENU'.
ENDMODULE.

MODULE status_200 OUTPUT.
  SET PF-STATUS 'CLIENT_IDENT'.
ENDMODULE.

MODULE status_210 OUTPUT.
  SET PF-STATUS 'REGISTER_CLIENT'.
ENDMODULE.

MODULE status_215 OUTPUT.
  SET PF-STATUS 'WELCOME'.
ENDMODULE.

MODULE status_220 OUTPUT.
  SET PF-STATUS 'LOG_IN'.
ENDMODULE.

MODULE status_230 OUTPUT.
  SET PF-STATUS 'CLIENT_MENU'.
ENDMODULE.

MODULE status_290 OUTPUT.
  SET PF-STATUS 'FINAL-GREETINGS'.
ENDMODULE.

MODULE status_300 OUTPUT.
  SET PF-STATUS 'EMPLOYEE_MENU'.
ENDMODULE.